social:
  - name: Github
    icon: github
    url: https://github.com/ppq1024
  - name: E-mail
    icon: mail
    url: mailto:ppq0x0400@outlook.com
gitalk:
  clientID: Ov23li2Zw0KTzG3sZ7XW
  repo: ppq1024.github.io
  owner: ppq1024
  admin: ppq1024
